### ISSUE TITLE
Error when users registered in device is too large?

### ISSUE THREAD

**Issue by csulit** [caobo171/node-zklib#22]
```
ZKError {
  err: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 4. Received 24
      at boundsError (internal/buffer.js:76:9)
      at Buffer.readUInt32LE (internal/buffer.js:210:5)
      at Buffer.readUIntLE (internal/buffer.js:168:17)
      at ZKLibTCP.getInfo (C:\Users\csulit\Documents\node-zklib-master\zklibtcp.js:461:22)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async ZKLib.functionWrapper (C:\Users\csulit\Documents\node-zklib-master\zklib.js:23:38)
      at async ZKLib.getInfo (C:\Users\csulit\Documents\node-zklib-master\zklib.js:182:16)
      at async test (C:\Users\csulit\Documents\node-zklib-master\test.js:10:15) {
    code: 'ERR_OUT_OF_RANGE'
  },
  ip: '192.168.139.81',
  command: '[TCP] undefined'
}
```

**Comment by caobo171** [comment]
this error occured when you use getUsers() right ? how many users in the device that you have @csulit  ?

**Comment by marhao** [comment]
how to fix this error @csulit
