### ISSUE TITLE
ZKError: TIMEOUT_ON_WRITING_MESSAGE upon client socket reconnect.

### ISSUE THREAD

**Issue by edwin1028** [caobo171/node-zklib#27]
Good day! I'm attempting to connect multiple devices and use socket.io to emit data to client side. At first load of the server everything works fine, It say's "ok tcp" and "ok udp" but after/upon reloading the client app im having a problem with the udp type device. Here is the error: 
```
 ZKError {
      err: Error: TIMEOUT_ON_WRITING_MESSAGE
      at Timeout.<anonymous> (C:\workspace\zktime-logs\backend\node_modules\node-zklib\zklibudp.js:101:20)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7),
      ip: 'XXX.XXX.XX.XX',
      command: '[UDP] undefined'
 }

```

Here is my code below:
```
constructor(server) {
    this.io = sio.listen(server);
    this.io
      .on("connection", (socket) => {
        devices.forEach(async (device, index) => {
          const zkInstance = new ZKLib(device.ip, 4370, 10000, 4000);
          try {
            await zkInstance.createSocket();
            console.log(await zkInstance.getInfo());

            await zkInstance.getRealTimeLogs((data) => {
              console.log(data);
            });
          } catch (e) {
            console.log(e);
            if (e.code === 'EADDRINUSE') {
            }
          }
        });
      });
  }
``

Thank you in advance for the help!

**Comment by Benitez25** [comment]
Hello, did you solve the problem?. That happens to me too

**Comment by redjanym** [comment]
@edwin1028 @Benitez25 have you managed to solve the issue? I'm working with a ZKTeco C3-100 Access Control device and i'm getting the same error.

```javascript
let zkInstance = new ZKLib('192.168.1.201', 4370, 10000, 4000);

    try {
        // Create socket to machine
        await zkInstance.createSocket()

        console.log(await zkInstance.getInfo())
    } catch (e) {
        console.log(e)
    }
```
This is my code

**Comment by zhfahan77** [comment]
any update facing same problem here,

![image](https://user-images.githubusercontent.com/18385348/107915760-485d1b80-6f8f-11eb-9167-3cab4cfa4a18.png)

**Comment by fernandomonterroso** [comment]
Tengo el mismo problema.

**Comment by jmikepaz** [comment]
same problem when try zkInstance.getTime()

**Comment by jmikepaz** [comment]
> same problem when try zkInstance.getTime()
new ZKLib(address, port, timeout , inport);
I resolve error timeout = 10000;

**Comment by merouanezouaid** [comment]
> any update facing same problem here,
> 
> ![image](https://user-images.githubusercontent.com/18385348/107915760-485d1b80-6f8f-11eb-9167-3cab4cfa4a18.png)


I fixed it you just need to remove await in the timeout method and it works perfectly fine for me

The code is in zklibtcp.js file:

```js
writeMessage(msg, connect) {
    return new Promise((resolve, reject) => {

      let timer = null
      this.socket.once('data', (data) => {
        timer && clearTimeout(timer)
        resolve(data)
      })

      this.socket.write(msg, null, async (err) => {
        if (err) {
          reject(err)
        } else if (this.timeout) {
          timer = setTimeout(() => {
            clearTimeout(timer);
            reject(new Error('TIMEOUT_ON_WRITING_MESSAGE'));
          }, connect ? 2000 : this.timeout)
        }
      })
    })
  }
```
I updated some functionalities and resolved most of the issues in my module based on this package 
Feel free to check it out:
https://github.com/merouanezouaid/zklib-js

**Comment by marwanzak** [comment]
had anyone solve it yet? I have the same issue with some devices and not all of them

**Comment by beatrx30** [comment]
My case is my ZKteco G2 was offline so i can't make a TCP connect to it, even though i can ping to the device 's IP. So make sure your device is online and be abled to connect. And If other computer is connecting to the attendence device, you still can connect to it by TCP, i dont use UDP so i don't know if it worked.
